# Generated by Django 2.0 on 2017-12-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='balance_story',
            field=models.TextField(blank=True),
        ),
    ]
